language: python
sudo: required

env:
    - ANSIBLE_VERSION: "2.4.3.0"

install:
  - sudo apt update -qq

script:
# Download test shim.
- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
- chmod +x ${PWD}/tests/test.sh

# Run tests.
- ${PWD}/tests/test.sh

notifications:
    # Always send email notification
    email:
        on_success: always
        on_failure: always
        on_start: always
        on_cancel: always
        on_error: always
    # Only notify ansible galaxy on success
    webhooks:
        urls:
            - https://galaxy.ansible.com/api/v1/notifications/
        on_success: always
        on_failure: never
        on_start: never
        on_cancel: never
        on_error: never
